server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/e-Anri/ms-mingeso.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}

  application:
    name: config-service





