server:
  port: 8888


spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/e-Anri/properties.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}